### ISSUE TITLE
Mention 

### ISSUE THREAD

**Issue by tomek-he-him** [bauerca/node-ensure#1]
Hi,

I’ve written a shim for [_raw-loader_](https://github.com/webpack/raw-loader) in node – called [_node-raw_](https://github.com/tomekwi/node-raw). Mainly for the purpose of testing and rapid development. Much in the same spirit as your _node-ensure_.

@bauerca would you mind mentioning it in this project?

**Comment by bauerca** [comment]
Sure thing. Done.

**Comment by tomek-he-him** [comment]
Thanks :)

**Comment by tomek-he-him** [comment]
Hi, I’m just writing to tell you I had some bad luck with _node-raw_ and deprecated it. It worked well as long as I developed my app under node. But webpack doesn’t seem to understand `require` wrapped in another function.

I even had [another go at the topic](https://github.com/tomekwi/isomorphic-ensure) which works smoothly, but [squeezes warnings out of webpack](https://github.com/webpack/webpack/issues/1028).
